// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://krawzklyjjqrmorhdwam.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtyYXd6a2x5ampxcm1vcmhkd2FtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5NTAzMTYsImV4cCI6MjA2ODUyNjMxNn0.nk6NlaZLqT1pGReCoVrxtDk9lSBPRDhREJgct8dzwLM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});